# --- Laptop Screen (Disabled) ---
monitor=eDP-1,disable

# --- External Monitors ---
# Move the first Dell to 0x0 to become the new primary anchor
monitor=desc:Dell Inc. DELL S2725DC 4YQMQC4,2560x1440@143.97,0x0,1.0

# Move the second Dell to start where the first one ends (2560 pixels)
monitor=desc:Dell Inc. DELL S2725DC DR13RC4,2560x1440@143.97,2560x0,1.0

# Workspaces
workspace = 1, monitor:desc:Dell Inc. DELL S2725DC DR13RC4
workspace = 2, monitor:desc:Dell Inc. DELL S2725DC 4YQMQC4
workspace = 3, monitor:desc:Dell Inc. DELL S2725DC 4YQMQC4
workspace = 4, monitor:desc:Dell Inc. DELL S2725DC DR13RC4
