# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(202422)
$foreground = rgb(F3EBD1)
$color0 = rgb(454A48)
$color1 = rgb(101F19)
$color2 = rgb(3A3326)
$color3 = rgb(4F3D2D)
$color4 = rgb(A63241)
$color5 = rgb(975A31)
$color6 = rgb(A6955C)
$color7 = rgb(E6DAB5)
$color8 = rgb(A1997E)
$color9 = rgb(162A22)
$color10 = rgb(4E4433)
$color11 = rgb(6A513C)
$color12 = rgb(DD4257)
$color13 = rgb(C97842)
$color14 = rgb(DDC67B)
$color15 = rgb(E6DAB5)
