-- ==================================================
--  KoolDots (2026)
--  Project URL: https://github.com/LinuxBeginnings
--  License: GNU GPLv3
--  SPDX-License-Identifier: GPL-3.0-or-later
-- ==================================================
-- User animation overrides template.
-- Use this to override defaults from lua/animations.lua.

-- Example:
-- hl.config({
--   animations = {
--     enabled = true,
--   },
-- })
--
-- hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "wind", style = "slide" })
