# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D3D3D3
background         #17140E
cursor             #5F5F62

active_tab_foreground     #17140E
active_tab_background     #D3D3D3
inactive_tab_foreground   #D3D3D3
inactive_tab_background   #17140E

active_border_color   #D3D3D3
inactive_border_color #17140E
bell_border_color     #9EA6AD

color0      #A1A0A0
color1		#9EA6AD
color2		#A2A09F
color3		#716C66
color4		#575451
color5		#464446
color6		#3A3531
color7		#5F6468
color8		#949BA1
color9		#D3DDE6
color10		#D8D6D3
color11		#968F89
color12		#736F6C
color13		#5E5A5D
color14		#4D4741
color15		#E1E6EA
