# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3EBD1
background         #202422
cursor             #A09782

active_tab_foreground     #202422
active_tab_background     #F3EBD1
inactive_tab_foreground   #F3EBD1
inactive_tab_background   #202422

active_border_color   #F3EBD1
inactive_border_color #202422
bell_border_color     #101F19

color0      #454A48
color1		#101F19
color2		#3A3326
color3		#4F3D2D
color4		#A63241
color5		#975A31
color6		#A6955C
color7		#E6DAB5
color8		#A1997E
color9		#162A22
color10		#4E4433
color11		#6A513C
color12		#DD4257
color13		#C97842
color14		#DDC67B
color15		#E6DAB5
