# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Vendor defaults for layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# LAYER RULES
layerrule = match:namespace rofi, blur on, ignore_alpha 0, animation slide
layerrule = match:namespace notifications, blur on, ignore_alpha 0, animation slide
layerrule = match:namespace quickshell:overview, blur on, ignore_alpha 0.5
layerrule = match:namespace wallpaper, blur on, ignore_alpha 0

# swaync + helper overlays
# Disable causes huge blue on notifications
#layerrule = match:namespace swaync-control-center, blur on, ignore_alpha 0
layerrule = match:namespace swaync-notification-window, blur on, ignore_alpha 0
layerrule = match:namespace com.aurora.keybinds_help, blur on, ignore_alpha 0
layerrule = match:namespace logout_dialog, blur on, ignore_alpha 0

#  Optional Layer rules
#  To Resolve blurred corners in rofi  Add to User config
#  SUPER SHIFT + E   Edit User Layer Rules
#layerrule = blur on, ignore_alpha 0, match:namespace rofi
#layerrule = blur on, match:namespace waybar
